### ISSUE TITLE
Flutter 2 update

### ISSUE THREAD

**Issue by zendamacf** [ryanhz/fluent-dart#2]
Hi, any chance of updating this package to support Flutter 2? Looks like it initially needs to update intl from 0.16.0 to 0.17.0.

**Comment by 12people** [comment]
Just as importantly, null-safety needs to be implemented.

**Comment by dvc94ch** [comment]
I guess this library is unmaintained?

**Comment by ryanhz** [comment]
Sorry I was very busy. Just upgrade to null safety.

Feel free to PR and contribute

**Comment by 12people** [comment]
@iot-d Perhaps you could merge the changes from your fork here?

**Comment by ryanhz** [comment]
I have upgraded to null safety yesterday.

**Comment by 12people** [comment]
@ryanhz Great! Thanks for pointing that out :)

Could you update the examples in the readme? I'm getting the `A value of type 'String?' can't be returned from the function 'about' because it has a return type of 'String'.` error when using `_bundle.format` — is the preferred way of dealing with that just go append ! at the end of every format call? (It doesn't seem like great practice to me, but that seems to be the way it's architectured, right?)

**Comment by 12people** [comment]
(Nevermind, forgot about the separate l10n_provider file — I'll be changing all instances of String into String?, then.)

**Comment by ryanhz** [comment]
Oh, I forgot readme.   This is the result of nullable.  Actually it return the same thing, it can return null previously as well (for example you pass in the wrong message id).
I suggest add a wrapper function to deal with null, for example, return `! id !` as default return value to indicate a missing id.
